<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJV8QxfR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJV8QxfR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJV8QxfR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJV8QxfR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJV8QxfR\App_KernelDevDebugContainer([
    'container.build_hash' => 'JV8QxfR',
    'container.build_id' => 'aef74ae5',
    'container.build_time' => 1715603335,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJV8QxfR');
